export const OPEN_DIALOG_WORKER = "OPEN_DIALOG_WORKER";
export const CLOSE_DIALOG_WORKER = "CLOSE_DIALOG_WORKER";

export const OPEN_LOADER_WORKER = "OPEN_LOADER_WORKER";
export const CLOSE_LOADER_WORKER = "CLOSE_LOADER_WORKER";

export const SIGNIN_WORKER = "SIGNIN_WORKER"
export const SIGNIN_FAIL_WORKER = "SIGNIN_FAIL_WORKER"